name: Create Release and Build Firmware

on:
  push:
    branches:
      - deployment

jobs:
  build:
    name: Build and Release Firmware
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PlatformIO
      uses: platformio/action-core@v2

    - name: Build firmware
      run: pio run

    - name: Archive firmware binaries
      run: |
        mkdir artifacts
        cp .pio/build/*/firmware.bin artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware-binaries
        path: artifacts/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: "Firmware Build ${{ github.sha }}"
        draft: false
        prerelease: false

    - name: Upload Firmware to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/firmware.bin
        asset_name: firmware.bin
        asset_content_type: application/octet-stream