name: Automated Firmware Release

on:
  push:
    branches:
      - main
      - test

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.SECRET_TOKEN }}
        default_bump: patch
        tag_prefix: v

    - name: Install PlatformIO
      run: pip install --upgrade platformio

    - name: Build Firmware
      run: pio run

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: .pio/build/station/firmware.bin
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/station/firmware.bin