name: Automated Firmware Release

on:
  push:
    branches:
      - main
      - test

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Determine Version Increment
      id: version
      run: |
        increment="patch"
        
        if git log -1 --pretty=%B | grep -qE "^feat:"; then
          increment="minor"
        elif git log -1 --pretty=%B | grep -qE "^break:"; then
          increment="major"
        fi
        
        echo "increment=$increment" >> $GITHUB_OUTPUT

    - name: Bump Version
      id: bump_version
      uses: christian-konrad/gh-action-bump-version@master
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        version-type: ${{ steps.version.outputs.increment }}

    - name: Install PlatformIO
      run: pip install --upgrade platformio

    - name: Build Firmware
      run: pio run

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: .pio/build/station/firmware.bin
        tag_name: ${{ steps.bump_version.outputs.newTag }}
        generate_release_notes: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/station/firmware.bin