name: Create Release and Build Firmware

on:
  push:
    branches:
      - deployment

jobs:
  build:
    name: Build and Release Firmware
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all tags
      run: git fetch --tags
      
    - name: Calculate next version
      id: version
      run: |
          # Hole das letzte Tag
          last_version=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Last version: $last_version"

          # Extrahiere die Teile der semantischen Version
          major=$(echo $last_version | cut -d. -f1 | sed 's/v//')
          minor=$(echo $last_version | cut -d. -f2)
          patch=$(echo $last_version | cut -d. -f3)

          # Inkrementiere den Patch-Level
          patch=$((patch + 1))

          # Baue die neue Version
          new_version="v$major.$minor.$patch"
          echo "New version: $new_version"

          # Exportiere die neue Version als Ausgabe
          echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Set up PlatformIO
      uses: platformio/action-core@v2

    - name: Build firmware
      run: pio run

    - name: Archive firmware binaries
      run: |
        mkdir artifacts
        cp .pio/build/*/firmware.bin artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware-binaries
        path: artifacts/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.new_version }}
        release_name: "Firmware Build ${{ env.new_version }}"
        draft: false
        prerelease: false

    - name: Upload Firmware to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/firmware.bin
        asset_name: firmware.bin
        asset_content_type: application/octet-stream