name: Create Release and Build Firmware

on:
  push:
    branches:
      - deployment

jobs:
  build:
    name: Build and Release Firmware
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Fetch all tags
      run: git fetch --tags
      
    - name: Calculate next version
      id: version
      run: |
          last_version=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Last version: $last_version"

          major=$(echo $last_version | cut -d. -f1 | sed 's/v//')
          minor=$(echo $last_version | cut -d. -f2)
          patch=$(echo $last_version | cut -d. -f3)

          patch=$((patch + 1))

          new_version="v$major.$minor.$patch"
          echo "New version: $new_version"

          echo "new_version=$new_version" >> $GITHUB_ENV
          
    - name: Build firmware
      run: pio run

    - name: List build directory contents
      run: ls -R .pio/build/

    - name: Archive firmware binaries
      run: |
        mkdir artifacts
        cp .pio/build/receiver/firmware.bin artifacts/receiver-firmware.bin
        cp .pio/build/transmitter/firmware.bin artifacts/transmitter-firmware.bin

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware-binaries
        path: artifacts/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        tag_name: ${{ env.new_version }}
        release_name: "Firmware Build ${{ env.new_version }}"
        draft: false
        prerelease: false

    - name: Upload Firmware to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/receiver-firmware.bin
        asset_name: receiver-firmware.bin
        asset_content_type: application/octet-stream

    - name: Upload Transmitter Firmware to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/transmitter-firmware.bin
        asset_name: transmitter-firmware.bin
        asset_content_type: application/octet-stream
